### ISSUE TITLE
Moment is undefined

### ISSUE THREAD

**Issue by szantner** [moment/moment-timezone#128]
I am using moment-timezone with moment.js, angularjs and angular-moment on node-webkit. I had to change the lines:

``` js
if (typeof define === 'function' && define.amd) {
        define(['moment'], factory);                 // AMD
    } else if (typeof exports === 'object') {
        module.exports = factory(require('moment')); // Node
    } else {
        factory(root.moment);                        // Browser
    }
```

to

``` js
if (typeof define === 'function' && define.amd) {
        define(['moment'], factory);                 // AMD
    } else if (typeof exports === 'object') {
        module.exports = factory(require('moment')); // Node
    } else {
        factory((typeof global !== 'undefined'? global : root).moment);                        // Browser
    }
```

so to avoid that problem. Of course maybe I am doing something completely wrong.

**Comment by kohenkatz** [comment]
This appears to still be an issue on [NW.js](http://nwjs.io/) apps, which have `global` and `window`.

```
TypeError: Cannot read property 'tz' of undefined
    at file:///C:/Work/console-build/src/js/lib/moment-timezone-with-data.js:22:12
    at file:///C:/Work/console-build/src/js/lib/moment-timezone-with-data.js:16:3
    at file:///C:/Work/console-build/src/js/lib/moment-timezone-with-data.js:18:2 
```

**Comment by tlindig** [comment]
The issues is still active in version 0.4.0.

Problem is the global loader for usage in browser

Line 16 in moment-timezone.js

```
} else {
        factory(root.moment);                        // Browser
}
```

`root.moment` is undefined.

change it to this should solve the problem.

```
} else {
        root.moment = factory(root.moment || {});                        // Browser
}
```

**Comment by gilmoreorless** [comment]
I'm closing off stale issues as they're very difficult to reproduce, and this project is now in maintenance-only mode. Feel free to open a new issue if this is still a problem.
