### ISSUE TITLE
Moment not working with Karma unit tests

### ISSUE THREAD

**Issue by leopoldjoy** [moment/moment-timezone#351]
Hello,

I use Moment in the following way:

    import moment from 'moment-timezone';
    // ...
    const userTimezone = moment.tz.guess();
    // ...

When I run my `ReactJS` components that use `moment` via [`karma`](https://github.com/karma-runner/karma) as unit tests, I get the following error:

    START:
    Chrome 50.0.2661 (Mac OS X 10.9.2) ERROR
      Uncaught Error: Cannot find module "./data/packed/latest.json"
      at /Users/myuser/myapp/tests.webpack.js:50215 <- webpack:///~/moment-timezone/index.js:2:0
    Chrome 50.0.2661 (Mac OS X 10.9.2) ERROR
      Uncaught Error: Cannot find module "./data/packed/latest.json"
      at /Users/myuser/myapp/tests.webpack.js:50215 <- webpack:///~/moment-timezone/index.js:2:0

Any idea why I might be getting these?

NOTE: This is a duplicate of this [issue](https://github.com/karma-runner/karma/issues/2156) filed on the `karma` GitHub page.

**Comment by leopoldjoy** [comment]
Resolved this issue by making these changes: https://github.com/karma-runner/karma/issues/2156
