### ISSUE TITLE
Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by dragonjet** [moment/moment-timezone#630]
Node 6.11.1
Elastic Beanstalk `Node.js running on 64bit Amazon Linux/4.2.1`

Our microservices started failing a few moments ago when creating new instances of the nodejs app.
```
Error: use-plugin: Could not load plugin /var/app/current/src/xxxx defined in /var/app/current/src/xxxx as a require call inside the plugin (or a module required by the plugin) failed: Error: Cannot find module 'moment' at require (internal/module.js:20:19) at VERSION (/var/app/current/node_modules/moment-timezone/moment-timezone.js:12:28) at Object.<anonymous> (/var/app/current/node_modules/moment-timezone/moment-timezone.js:17:2) at require (internal/module.js:20:19) at Object.<anonymous> (/var/app/current/node_modules/moment-timezone/index.js:1:93).
```
I belive this is because of the latest 0.5.18 publish

Our current workaround is to use strict version in our `package.json`
```
"moment-timezone": "^0.5.14",
```
into
```
"moment-timezone": "0.5.14",
```
so the servers will pull strictly that version. I do not know if 0.5.17 works, as these are the ones in our package.json. I still have to update all our production repos, so I don't have time now to test.

**Comment by ellenaua** [comment]
Hi @dragonjet I rolled back change which was done today, until we find out why it's breaking things.
peerDependency should be installed if it's not present, so it's strange that moment.js is not found.
You can definitely use moment-timezone `0.5.17` and `0.5.19`

**Comment by dragonjet** [comment]
thanks :+1:
we'll update our packages to `0.5.17` for now, and will add `moment` to all repos, just in case :)

**Comment by rpellerin** [comment]
peer dependencies are no longer automatically downloaded, since npm 3 ([source](https://blog.npmjs.org/post/110924823920/npm-weekly-5)).
However, having `moment` declared as a peer dependency offers much more flexibility and allow bundles to be more lightweight, as it prevents from having several versions of `moment` installed.

**Comment by rpellerin** [comment]
Hi @ellenaua any chance we put `moment` back in the `peerDependencies`?

**Comment by ellenaua** [comment]
@rpellerin I think it should be released as moment-timezone 0.6.0

**Comment by EnixCoda** [comment]
It's happening on latest version of `moment`(v2.22.2) and `moment-timezone`(v0.5.21).

It took a lot of my time to figure out why my app keeps failing because of `moment.tz was not defined`. And it might be take lots of other people's time if someone just create a new project with latest versions installed, they should have this problem too.

Looking forward to release of `0.6.0` 😃

**Comment by Americas** [comment]
After almost a year, can we have a version of `moment-timezone` with `moment` as a peer dependency?
